- app.py
- arxiv/base/config.py
- arxiv/base/routes.py
- arxiv/base/templates/base/footer.html
- arxiv/base/templates/base/header.html
- arxiv/base/templates/base/macros.html
- requirements/test.txt
@eawoods This is to address building URLs for things in the base templates. It seems that the biggest constraint on this functionality is that it needs to be possible to make changes to these URLs without touching code (since base will be almost everywhere). The most straightforward way to do this is via configuration. So in this implementation, a function called ``config_url(target: str) -> str`` gets injected into the template context; it looks for and returns a configuration variable called ``ARXIV_[TARGET]_URL``.
> ARXIVNG-204 implemented config-driven URL builder for base templates

- arxiv/base/templates/base/head.html
All other elements are skipped. Since we haven't introduced abstracts yet, the "mathjax" class has only been applied to the title in the search results.
This PR also introduces two other minor changes:
1. disable multi-line, black-bordered box around TeX could not be processed by MathJax; it now looks like the rest of the paragraph
2. hide grey rendering status box that appears at the bottom of the page on page load; it was distracting to some users and doesn't provide much useful feedback anyway. Note that it's also possible to disable the greying of the TeX elements that MathJax has queued to process, but I haven't made that change here.
> Update MathJax config to only target elements with "mathjax" class

- arxiv/base/config.py
- arxiv/base/globals.py
- arxiv/base/logging.py
- arxiv/base/tests/test_logging.py
- requirements/test.txt
- setup.py
This adds the module ``arxiv.base.logging``, which provides a function ``getLogger`` -- it works just like the builtin ``logging.getLogger``, but with a simpler interface ( ``getLogger(name: str, stream: TextIO)`` ). It sets some defaults that should be applied consistently across all arXiv services, so that we can parse application log messages in a consistent way.
> ARXIVNG-392 ARXIVNG-391 added logging module with reasonable defaults

- arxiv/base/templates/base/macros.html
For parity with classic search template header and simple search (plus help pages).
> ARXIVNG-414 add fields to header search

- Pipfile
- Pipfile.lock
- arxiv/base/agent/__init__.py
- arxiv/base/agent/exceptions.py
- arxiv/base/agent/tests.py
- setup.py
(from docs in PR)
> We use Kinesis streams to broker notifications that concern multiple services
in the arXiv system. For example, at publication time, the publication process
generates notifications about new arXiv papers so that services like search
can update themselves.
> This module provides a base class for building agents with Kinesis streams,
:class:`.BaseConsumer`. The objective is to provide all of the
stream-management (e.g. checkpointing) and error-handling boilerplate needed
for any Kinesis consumer, so that we can focus on building the idiosyncratic
functional bits in arXiv services.
> You (the developer) should be able to create a minimal agent by:
> 1. Defining a class that inherits from :class:`.BaseConsumer`
> 2. Defining an instace method on that class with the …
> ARXIVNG-281 introduced base class and tools for Kinesis consumers

- arxiv/license.py
- arxiv/tests/test_license.py
This is mostly a conversion of the essentials from `arxiv-lib:arXiv::Config::Licenses`.
> Add license definitions to arxiv-base and simple test

- setup.py
Fixes:
- ARXIVNG-806: Move License information to arXiv-base
- ARXIVNG-849: Update base categories to include those without subject class
> Pre-release merge for base-0.7

- arxiv/base/templates/base/header.html
- setup.py
Note that ``arxiv.base`` does not (and should not) depend on ``arxiv.users``. The template is un-opinionated about how``request.session.user.username`` gets set. 
The best way to see this in action is to install arXiv base from this branch into another app (e.g. search), and make requests with an auth token. See https://github.com/cul-it/arxiv-auth#generating-auth-tokens
> ARXIVNG-1059 enabled auth context in header template when user session is available

- arxiv/base/__init__.py
- arxiv/base/alerts.py
- arxiv/base/routes.py
- arxiv/base/templates/base/base.html
- arxiv/base/tests/test_alerts.py
- setup.py
ARXIVNG-1101 Renames ``arxiv.base.messages`` to ``arxiv.base.alerts``
ARXIVNG-1127 Introduces ``arxiv.base.alerts.flash_hidden``, which can be used to send small amounts of structured data across requests (e.g. on redirect).
> ARXIVNG-1127 ARXIVNG-1101 Alerting

- arxiv/base/templates/base/macros.html
- arxiv/util/serialize.py
- arxiv/util/tests/test_serialize.py
Adds ``arxiv.util.serialize.ISO8601JSONEncoder`` and ``.ISO8601JSONDecoder``, and convenience functions ``.loads`` and ``.dumps``.  For background on JSON encoders/decoders, see https://docs.python.org/3/library/json.html#encoders-and-decoders.
> ARXIVNG-971 added ISO8601JSONEncoder and ISO8601JSONDecoder

- Pipfile
- Pipfile.lock
- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
- arxiv/identifier/__init__.py
- arxiv/identifier/tests.py
I refactored ``arxiv.base.urls.links`` to use the [``bleach``](https://bleach.readthedocs.io/en/latest/) package from Mozilla. It is a little more user-friendly than maintaining our own core code for matching/replacing identifiers and/or URLs. I combined the regex that was already there for DOIs, arXiv IDs, and URL cases not already handled by bleach with the core bleach URL regex. I then wrote some [callbacks](https://bleach.readthedocs.io/en/latest/linkify.html?highlight=callbacks#callbacks-for-adjusting-attributes-callbacks) to alter link text, add CSS classes (new), add ``rel`` attribute, generate URLs for arXiv IDs and callback URLs for DOIs, etc.
The tests are basically the same, I just updated them to reflect the classes, rel, and other attributes. But the matching/replacing …
> ARXIVNG-250 Linkification in abs view should not choke on parentheses

- .travis.yml
- Pipfile
- Pipfile.lock
- README.md
- arxiv/base/__init__.py
- arxiv/base/app_tests.py
- arxiv/base/config.py
- arxiv/base/factory.py
- arxiv/base/routes.py
- arxiv/base/static_test/test.md
- arxiv/taxonomy/category.py
- setup.py
- tests/run_app_tests.py
- upload_static_assets.py
This sets up a coherent URL strategy for serving static files. Goals:
- Be able to use multiple versions of base in different apps without clobbering shared static files
- Keep app and blueprint static files separate in S3
- Make sure the Flask-S3 integration works
From README.md:
...
In your ``config.py``, be sure to set ``APP_VERSION`` to the current semantic
version of the app. For example:
```python
APP_VERSION = "1.4.2rc5"
```
...
Base does a little bit of work for you to keep static files from different apps and versions sorted. The ``Base`` component will automatically set  your app's [``static_url_path``](http://flask.pocoo.org/docs/1.0/api/#flask.Flask.static_url_path) using the name of the app and the value of  ``APP VERSION`` in your config (see above) to ``/static/[app name]/[ …
> ARXIVNG-1015 set up coherent URL strategy for static files, including S3 integration

- .gitignore
- docs/source/arxiv/arxiv.base.agent.rst
- docs/source/arxiv/metadocs.rst
- docs/source/conf.py
- docs/source/index.rst
- update-docs.sh
In this PR I add the meta-documentation, correct an issue in arxiv.base.agent and update https://arxiv.github.io/arxiv-base
The intersphinx modules are not working, I suspect this is due to missing `objects.inv` files. I'll open another ticket to review those:
```
loading intersphinx inventory from https://cul-it.github.io/arxiv-base/objects.inv...
WARNING: failed to reach any of the inventories with the following issues:
WARNING: intersphinx inventory 'https://cul-it.github.io/arxiv-base/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: ('intersphinx inventory %r not fetchable due to %s: %s', 'https://cul-it.github.io/arxiv-base/objects.inv', <class 'requests.exceptions.HTTPError'>, HTTPError(...))
```
> Adding meta-documentation and updating github.io ARXIVNG-1624

- arxiv/mail/templates/html-sample.html
- arxiv/mail/templates/license.txt
- arxiv/mail/templates/plaintext-sample.txt
- arxiv/mail/templates/readme.md
Not yet Jinja-ized, wanted to get your look at this first and make sure I was 100% going in the right direction.
One can spend far too much time trying to capture whether all the test cases have been met - finally I decided to pick a boilerplate, add in some useful things from another boilerplate, and call it good enough until we test it.
Need to do: add a PNG version of the arXiv logo to static files so that it can be referenced in the email template. SVG renders nicely in browsers and some email clients, but is sketchily supported in others.
> ARXIVNG-1673 Initial draft of email templates

- Pipfile.lock
- arxiv/mail/__init__.py
- arxiv/mail/mail.py
- arxiv/mail/tests/__init__.py
- arxiv/mail/tests/test_mail.py
That's pretty much it. Looking at arXiv-Lib, that's pretty much the core of what we're doing (without wonderful HTML). On top of this we can add convenience functions for rendering templates...but basically all you need is:
```python
from flask import render_template
from arxiv import mail
mail.send("foo@user.edu", "Some arXiv for you", 
render_template("my/template.txt", **context), 
html_body=render_template("my/template.html", **context))
```
> ARXIVNG-1376 a simple sendmail-based method for sending e-mail 

- arxiv/base/config.py
- arxiv/base/filters.py
- arxiv/base/templates/base/macros.html
- arxiv/util/tests/test_tex2utf.py
- arxiv/util/tex2utf.py
This adds some missing URL definitions that went missing:
* `abs`
* `abs_by_id`
* `clickthrough`
There are also some minor fixes to filters and the `abs` macro:
* add `abstract_lf_to_br` filter
* add Markup awareness to tex2utf filter
* proper escaping
With this branch activated on browse, all tests pass. A separate PR for browse is forthcoming.
> ARXIVNG-1719: Add missing URLs and filter fixes

- .travis.yml
- arxiv/base/filters.py
- arxiv/base/templates/base/macros.html
- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
First, the abs macro templates were expecting a single DOI were explicitly using the a DOI filter and a click through filter. 
Second, when the abs macro template was switched to the links.py urlize, the DOI text was "this  URL"
That was due to the bleach linkifier applying all of the attribute callbacks. The external ref callback is changing the _text to "this URL"
So this PR refactors link.py to add a kind -> callbacks Dict.
link.py is also refactored to no longer produce one bleach linkifier object per call to link.urlizer() but to return a function composed of each kind of linkifier. Each kind of linkifier is configured independently by as patterns and callbacks.
This PR also adds nofollow and noopener to external links.
> Fixes bug "Links for Multiple DOIs on abs page are garbled"

- arxiv/base/filters.py
- arxiv/base/templates/base/macros.html
- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
Fixes regression with DOIs in base by adding a specialized urlizer kind for the abs DOI field.
This will be needed for browse 0.2.1
https://arxiv-org.atlassian.net/browse/ARXIVNG-2049
> DOI linking regression 

- arxiv/base/templates/base/base.html
- arxiv/base/templates/base/head.html
Whenever it's time to pull this in -- here is the tracking code for the new Matomo.
I checked with Chris and he said that it is OK to have the new code implemented on some pages and the old code on others if we want to or need to; the log import would cover that. He did say, however, NOT to have both trackers running on the same page so that it doesn't get double counted.
For the donate button tracking, this needs to get implemented for arxiv-docs specifically.
The new Matomo has other options if we need to configure download formats to track or any other custom variables. I tried to just match what we had in the old Piwik for now.
> add new Matomo tracking code

- arxiv/base/templates/base/macros.html
The crosses are in a different order for https://beta.arxiv.org/abs/0906.3421 compared to https://beta.arxiv.org/abs_classic/0906.3421 
Classic: Statistical Mechanics (cond-mat.stat-mech); Mathematical Physics (math-ph) 
NG: Mathematical Physics (math-ph); Statistical Mechanics (cond-mat.stat-mech) 
This fixes the order of the secondaries. 
https://arxiv-org.atlassian.net/browse/ARXIVNG-2066
This will need to be in a release of base for use in browse-0.2.1.
> Sorting /abs secondaries by ID

- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
> ARXIVNG-2068: Urlize no longer turns category names like math.CO into urls

- Pipfile
- Pipfile.lock
- arxiv/base/__init__.py
- arxiv/base/config.py
- arxiv/base/tests/test_urls.py
In some cases, we want an app to handle all of its static files, e.g. when deploying in a development environment. Setting the configuration param ``RELATIVE_STATIC_PATHS`` to True will cause ``/{RELATIVE_STATIC_PREFIX}`` to be prepended to the static paths for base assets. This should have no impact on static paths for blueprints.
This helps to solve the problem that static URLs don't work when a site is deployed as a container on a sub path.
> ARXIVNG-2073 add support for relative static paths

- Pipfile
- Pipfile.lock
- arxiv/base/__init__.py
- arxiv/base/config.py
- arxiv/base/urls/__init__.py
- arxiv/base/urls/tests/test_urls.py
- setup.py
Earlier versions of this module built Werkzeug routing machinery (Rules, Maps, etc) on the fly. This led to serious memory leaks. As of v0.15.6, :class:`.Base` uses :func:`register_external_urls` to set up external URL handling, which registers a single :class:`.MapAdapter` on a Flask app. This adapter is in turn used by :func:`external_url_handler` on demand.
> ARXIVNG-2085 addressing memory leak in production

- Pipfile
- Pipfile.lock
- arxiv/base/logging.py
- arxiv/integration/kinesis/consumer/__init__.py
- arxiv/integration/kinesis/consumer/exceptions.py
- arxiv/integration/kinesis/consumer/tests.py
- setup.py
The Kinesis consumer has some retry handling, e.g. when waiting for the stream to be available. https://github.com/arXiv/arxiv-base/tree/feature/ARXIVNG-1970/arxiv/integration/kinesis 
This is currently not configurable; it should be easy to alter this in a subclass without overriding whole methods. 
This PR eliminates the simple ``retry`` decorator in that module, and uses [``retry``](https://pypi.org/project/retry/) instead. Parameters for retry can be passed to the ``BaseConsumer`` constructor, and are stored in the public attribute ``retry_params``. So the retry behavior can be configured via the app config (``KINESIS_RETRY_x`` params), or a subclass can easily intervene on  ``retry_params``. 
Not perfect. But an improvement.
> ARXIVNG-2042 Make retry behavior in base Kinesis consumer easier to modify

- arxiv/base/filters.py
- arxiv/base/templates/base/macros.html
This changes the /abs page macro so it only does arxiv-id urlization on the title.
I've made tests for this in arxiv-browse.
https://arxiv-org.atlassian.net/browse/ARXIVNG-2109
> Removes unwanted urlization in title field of /abs

- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
This is a bit of an odd one. There were some strange errors in the production logs that were persistent but not immediately reproducible.
These turned out to be related to bleach.  https://bleach.readthedocs.io/en/latest/clean.html
https://arxiv-org.atlassian.net/browse/ARXIVNG-2107
I reproduced this on my laptop and fixed it by making the bleach object thread local. 
I can reproduce error on my laptop by:
- running apache,
- with wsgi with 16 threads,
- configiuring arxiv-browse to not use the DB
- then running "ab -c 300 -t 120 http://localhost/test/abs/1411.4413"
Erick and Jamie I'm wondering your thoughts on:
1. Are thread locals a good way to solve this problem?
2. Is the dynamic creation of the thread local bleach objects in _deferred_thread_local_linker_of_kind a good way to …
> Fixes race condition due to multithread use of bleach

- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
See abstract in https://arxiv.org/abs/1806.04641 
It can be urlized, but should preserve the text "arXiv.org" with link to https://arxiv.org 
Linking to arXiv IDs to should not be affected.
> "arxiv.org" should not be generically urlized with "this http url"

- arxiv/base/middleware/__init__.py
- arxiv/base/middleware/base.py
- arxiv/integration/api/service.py
- setup.py
This adds support for additional (arbitrary) config params in the base service integration in ``arxiv.base.integration.service``. Any params in the config that start with the service name (in upper case) will be passed as kwargs to the ``HTTPIntegration`` constructor.
> ARXIVNG-2188 support for extra config params in base service integration

- arxiv/forms/csrf.py
- arxiv/forms/tests.py
ARXIVNG-1920 (NG auth session should not clobber built-in Flask session interface) moved the authn/z session information from ``flask.request.session`` to ``flask.request.auth``. This is currently an optional feature (enabled with ``AUTH_UPDATED_SESSION_REF``), but ARXIVNG-1944 (The authenticated session should be named request.auth by default) will remove support for ``.session``. 
Currently, the CSRFForm provided in arxiv.forms.csrf relies on the older ``.session`` accessor. This prevents using ``AUTH_UPDATED_SESSION_REF``, and will break when ARXIVNG-1944 is released.
See https://github.com/arXiv/arxiv-base/blob/master/arxiv/forms/csrf.py#L146
> ARXIVNG-2186 csrf form can use either request.session or request.auth for authn context

- arxiv/base/filters.py
- arxiv/util/tests/test_tex2utf.py
- arxiv/util/tex2utf.py
The fix for https://arxiv-org.atlassian.net/browse/ARXIVNG-1612 disabled tex2utf for TeX letters and greek symbols when only the greek symbols should have been disabled. 
This PR changes tex2utf() so there is a greek flag which only enables or disabled greek TeX to UTF8 translation.
The Jinja HTML filter tex2utf_no_symbols() that is used for the abstract is also changed to to disable greek but enable other letter TeXisms. 
https://arxiv-org.atlassian.net/browse/ARXIVOPS-805
> Only disable greek textism, not letter ones

- .gitignore
- arxiv/integration/api/service.py
Fixes #146 . I made this use an instance method so that the config could be defined programmatically.
> made retry configurable in base HTTPIntegration

- arxiv/base/templates/base/base.html
Added new "skip" link, only visible to screen readers, above header. Required under WCAG 2 standards.
> ARXIVNG-2745 - added accessible "skip" link

- arxiv/base/alerts.py
- arxiv/base/templates/base/base.html
- arxiv/base/templates/base/macros.html
"There are are error messages originating from arxiv-base that are displaying above the pagination. We should consolidate error display in the submit-ui templates to below the page title."
https://arxiv-org.atlassian.net/browse/ARXIVNG-2917
> Moves alerts to macros to allow control of them in submission-ui

- arxiv/base/static/css/arxivstyle.css
- arxiv/base/static/sass/_overrides.sass
Very minor: changes the default text color of headers in success messages from black to white to meet a11y contrast guidelines.
> changes default success message header color

- arxiv/base/templates/base/macros.html
This commit makes a few small edits to the abs macro in response to the new mobile-friendly abs changes. Those abs changes are in browse branch ARXIVNG-3004.
Changes:
- moving the mobile download button from the top of the page to in between authors and abstract (in response to user requests).
- adding some new classes to elements (not visible on desktop).
- moving the submitted date element above the title (visible on all screen widths).
This ticket has one pending item and is not ready to merge (ARXIVNG-3032) but wanted to get this branch up for review and collaboration.
Screenshots (mobile and desktop) are below for reference.
> ARXIVNG-3004 edits macros.html (abs macro) for mobile-friendly abs page

- Dockerfile
Docker image would not build correctly due to an obsolete package url. I replaced obsolete url with the new url for package and build completes successfully.
You might want to verify that you can create the image using: 
#git clone git@github.com:arXiv/arxiv-base.git
#git checkout -b ARXIVNG-3432
#'docker build --tag arxiv/base:0.12 .'
> ARXIVNG-3432: Fix arXiv/base Docker image

- Pipfile
- Pipfile.lock
- arxiv/release/dist_version.py
- upload_static_assets.py
Changes to dist_version so get_version returns a valid python version when there is no git version and no release version. 
The python packaging tools fail or silently do incorrect behavior when there are invalid package version strings.
Also, this adds a confirmation to the FlaskS3 upload of static assets.
> Some changes to the dist_version

- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
- arxiv/release/README.md
- arxiv/release/dist_version.py
- arxiv/release/tag_check.py
The DOI link in the abs metadata now accepts a very broad range
of values to trun into DOI links.
DOI links in other areas like the abstract are unaffected.
ARXIVNG-3423
> Changes abs page DOI link to handle more cases.

- Dockerfile
Switches from IUS python36u to EPEL python3 due to IUS no longer
providing python36u.
https://github.com/iusrepo/packaging/issues/7
ARXIVNG-3570
> Fixes python36u docker build error

- Pipfile.lock
- arxiv/base/templates/base/macros.html
- arxiv/base/urls/links.py
- arxiv/base/urls/tests/test_urlize.py
- arxiv/taxonomy/definitions.py
- arxiv/util/authors.py
- arxiv/util/tests/test_authors.py
- setup.py
* changes DOI linking and display to follow CrossRef and DataCite best practices:
* link to https://doi.org/
* always display the full link
* fixes bug with back-propagation of author affiliations
* corrections to category descriptions
* defines `econ.GN` as a general category
> Pre-release merge for arxiv-base v0.17.3

- arxiv/base/static/js/member_acknowledgement.js
- arxiv/base/templates/base/header.html
The typo is here: https://dev.arxiv.org/user/
There's also some member js that overwrites it, and needs to be updated.
Looks like we've transitioned to using the .venv dir in the project.
Prod auth is using:
arxiv-auth                       1.0.0rc3
arxiv-base                       1.0.0a3
Prod browse is using:
arxiv-base 1.0.0a5
Looks like auth is being worked on now. Probably BrianC, along with browse.
> ARXIVCE-700: fix donate url

- arxiv/base/config.py
- pyproject.toml
Adds and cleans up some paths.
Adds separate servers for auth, submit, search and canonical. By default these are all the same as BASE_SERVER but could be switched if devops people wanted.
ARXIVCE-737
> Adds paths, adds separate severs for auth, submit, search and canonical

- arxiv/taxonomy/definitions.py
If there is an error with interpreting a category, but a Category object is required, it can now be assigned a invalid Category type
> created category definitions for errors to handle edge cases

- arxiv/taxonomy/category.py
- arxiv/taxonomy/taxonomy_test.py
this change is to support the creation of custom categories if unknown categories are created in our system. It stops category objects from being replaced with ones from CATEGORIES if they already have the same canonical id
> only replace Category object if canonical one is different

- gcp/service_auth/tests/test_get_token.py
- pytest.ini
(2) Make the test to run from the arxiv-base directory
> (1) Not select the with_op by default as you may not have 1password CLI

- arxiv/legacy/papers/dissemination/reasons.py
- arxiv/legacy/papers/dissemination/tests/test_reasons.py
Changes the parameter from a string for the GS URL to a `FileObj` so it is more general.
Forces `reasons()` to have a `dict` passed to it instead of using the global.
> Changes how reasons file is loaded.

- arxiv/ops/arxiv_stats/parse_paperid_remoteaddr_from_weblogs.sh
This extracts pdf download counts of (paper_id, remote_addr) from web logs.
It's an intermediary step in counting pdf downloads by category.
> ARXIVCE-1264: parse and count pdf downloads per ip

- arxiv/document/version.py
This would have been working when we were using .abs based metadata and regressed when we moved to db based metadata.
ARXIVCE-1745
> Fix to formats for PDF only papers

- arxiv/base/__init__.py
Removes unnecessary rollback on error. The existing call to Session.remove() would already do this if there was an open transaction.
This call was the source of some errors in arxiv-browse. Errors during the `.remove()` call will could still happen but this change will avoid rollbacks when there are no changes and in `READ_UNCOMMITTED`.  arxiv-browse runs in `READ_UNCOMMITTED` and makes no INSERT or UPDATEs.
The Sqlalchemy docs say (sqlalchemy.scoping.scoped_session.close())
"This expunges all ORM objects associated with this  `_orm.Session`, ends any transaction in progress and
`releases` any `_engine.Connection` objects which this  `_orm.Session` itself has checked out from associated  `_engine.Engine` objects. The operation then leaves the  `_orm.Session` in a state which it may be …
> Change to flask sqlalchemy db session close

- arxiv/base/__init__.py
- arxiv/base/static/js/member_acknowledgement.js
>  Change to flask sqlalchemy db session close

- arxiv/base/urls/links.py
This will match all latin-1 TLDs. Old code used a list from bleach.linkifier, which will always be out of date.
> ARXIVCE-2389 new generic regex [a-z][a-z]+ 

- arxiv/ops/db_subset/clone_subset.py
as such, importing this file causes an import error.
> There is no `engine` in arxiv.db (any more?)

- arxiv/config/__init__.py
This reverts the config change for "READ UNCOMMITTED", which was a one line in #325 , without a `git revert`, so that we keep the rest of the healthy changes that reached master.
> soft revert for #325

- .github/workflows/pullreqeust_tests.yaml
- arxiv/auth/openid/tests/test_keycloak.py
Chromium and its driver are snap based and it does not work with ACT. IOW, for testing, you don't want to rely on snapd up and running. I switched to use Firefox ESR since it is .beb based which in turn result in using the driver. 
Note that, this means the gecko driver is external and could become obsolete. When it happens, it may need to update the driver version which is unfortunate but the alternative is to be stuck with Chrome driver which is 20+ versions behind the stable Chrome stable release.
> Use Firefox instead of Chromium for Keycloak test

- arxiv/identifier/test_arxiv_identifier.py
- arxiv/ops/fastly_log_ingest/README.md
- arxiv/ops/fastly_log_ingest/app.py
- deploy/Dockerfile-fastlylogingest
Adds `try/catch` to WorkItem loop
Adds README
Adds SIGTERM handling for quick finishing of queue on shutdown
Has both a PREFERRED_PER_BATCH and MAX_PER_BATCH
Better date handling
Fixes `notify()`
Before the changes this did about 200 messages per sec, after it does about 300.
> Fixes some fastly_log_ingest problems

- poetry.lock
- pyproject.toml
I managed to successfully use the new "extra" via a cloud function with
```
arxiv-base [postgres] @ git+https://github.com/arXiv/arxiv-base@1021ddae5ecc5620c149ccb67ccf0a4a2228b389
```
added to requirements.txt
> add extra optional dependency for postgres

- .github/workflows/pullreqeust_tests.yaml
- arxiv/auth/openid/README.md
- arxiv/auth/openid/oidc_idp.py
- arxiv/auth/openid/tests/test_keycloak.py
It turns out that Gecko driver is updated so it's a good timing to update the tests.
"latest" went to v0.36 while the gecko driver file was named v0.35 and the test failed with 404.  For now, the gecko driver is locked at v0.36. which should be more stable link.
docstring format fixed.
> Add ssl cert check option for oidc client. needed to run it with self-signed cert for local dev
