arXiv/arxiv-base

README.md
app.py
baseui/config.py
baseui/factory.py
baseui/routes.py

@eawoods What do you think of this?

ARXIVNG-163 added minimal flask app for verification/testing

---

arxiv/taxonomy.py
tests/test_arxiv_taxonomy.py

This is essentially a conversion of the original Perl code but consolidated in a single file. I'm not sure we need more complexity than this at the moment but welcome any suggestions that could help make our lives easier later.

Simple dict-based representation of the arXiv category taxonomy.

---

arxiv/base/exceptions.py

added pagetitle to error pages

---

arxiv/base/templates/base/head.html

Fix MathJax config

---

arxiv/taxonomy.py
arxiv/tests/test_taxonomy.py

This adds missing categories (e.g. hep-* and others) to the `CATEGORIES` struct and a new key `is_active` to each category entry. `CATEGORIES_ACTIVE` contains only categories where `is_active` is `True`.

Add missing categories to CATEGORIES; add CATEGORIES_ACTIVE; misc fixes.

---

arxiv/base/config.py

Needed by https://culibrary.atlassian.net/browse/ARXIVNG-1031

Adds search by archive URL route

---

arxiv/base/templates/base/footer.html
arxiv/base/templates/base/header.html

as suggested in review; final changes prior to minting base 0.12.1.

slight change to wording and punctuation in footer and header

---

README.md
arxiv/base/config.py
arxiv/base/templates/base/footer.html

Footer links remodeled per meeting with Jim and Janelle on 2/6/19.
Donate link not included; was put on hold for now.

ARXIVNG-1666 ARXIVNG-1667 remove FAQ, finalize footer

---

arxiv/base/config.py
arxiv/base/templates/base/footer.html

Add privacy policy link to footer

---

Pipfile
Pipfile.lock
arxiv/base/templates/base/footer.html

Updates to footer to adjust for fourth column. (note how much easier this one was, <3 Bulma)

ARXIVNG-1918 add styles for four column footer

---

arxiv/base/config.py

These can probably be updated at this point.

update login and logout URL definitions

---

arxiv/base/__init__.py
arxiv/base/tests/test_static_urls.py

This updates the ``Map`` that the Flask app uses for (among other things) ``url_for()``.

ARXIVNG-2114 update app url_map when changing its static_url_path

---

arxiv/taxonomy/definitions.py
arxiv/taxonomy/tests.py

See https://arxiv-org.atlassian.net/browse/ARXIVNG-2179
I also fixed some inconsistencies in the category descriptions for some of the existing aliases; I don't expect this will cause any controversies but let me know if your disagree.

ARXIVNG-2179: new category, new aliases

---

arxiv/taxonomy/category.py

The current function only checks ARCHIVES_SUBSUMED, it needs to check CATEGORY_ALIASES as well. 
https://arxiv-org.atlassian.net/browse/ARXIVNG-2223

check CATEGORY_ALIASES in canonical function

---

arxiv/forms/csrf.py
arxiv/forms/tests.py

Also makes it configurable on object.
Fixes https://github.com/arXiv/arxiv-submission-ui/issues/87

Increases CSRF timeout

---

arxiv/taxonomy/category.py
arxiv/taxonomy/definitions.py
setup.py

Fixes:
- ARXIVNG-2223 - Category.canonical in arxiv.taxonomy.category does not return correct canonical category
- ARXIVNG-2202 - CSRF timeout is too short

Pre-release merge for v0.15.9

---

arxiv/taxonomy/definitions.py

This just adds is_general to the categories. The categories marked as general are from arXiv::Categories.pm.
ARXIVNG-2456

Adds is_general to CATEGORIES

---

arxiv/base/templates/base/footer.html

New small edits to footer to improve stacking on mobile.

ARXIVNG-1543 - footer edits

---

Pipfile
Pipfile.lock
arxiv/base/config.py
arxiv/base/templates/base/analytics_macros.html
arxiv/base/templates/base/base.html
arxiv/base/templates/base/head.html
arxiv/forms/tests.py

This adds analytics configuration options and also moves the analytics trackers into macros.

ARXIVNG-2959: make analytics configurable

---

.travis.yml

These are some changes that will hopefully fix the strange behavior we are seeing in travis.
I'll squash these since I was making a bunch of commits to test travis.

Travis testing fixes

---

Pipfile
Pipfile.lock
arxiv/release/dist_version.py
upload_static_assets.py

Fixes bug with get_version where it would return None from get_pkg_version.
Also adds a confirmation to upload_static_assets.py

Fixes None from get_version()

---

arxiv/taxonomy/definitions.py

based on mod feedback, this PR updates the description of stat.ML in base to:
Covers machine learning papers (supervised, unsupervised, semi-supervised learning, graphical models, reinforcement learning, bandits, high dimensional inference, etc.) with a statistical or theoretical grounding.

updates stat.ML description

---

arxiv/taxonomy/definitions.py

updating the taxonomy file to match changes in PR 78 to arxiv-lib.

updated econ.GN description

---

arxiv/taxonomy/definitions.py

Adds category descriptions to many physics areas.

ARXIVOPS-1433: physics category descriptions

---

arxiv/base/config.py

Minor change that updates the acknowledgement url in the browse header.

updates acknowledgement url

---

arxiv/base/urls/links.py

https://arxiv-org.atlassian.net/browse/ARXIVCE-330

ARXIVCE-330: add .xyz domains to the bleach tlds

---

arxiv/ops/fastly_gs_logs_to_cit.py
docs/source/index.rst
poetry.lock
pyproject.toml

Script to move fastly logs from GCP GS to CIT /data/logs_archive.
ARXIVCE-1120

Fastly logging to CIT /data/logs_archive

---

arxiv/files/fileformat.py

set different file formats to have to appropriate content type and encoding types defined

gzip files should be content type gzip.

---

arxiv/document/metadata.py

Swap order of acm-class and msc-class to conform to schema.

---

arxiv/integration/fastly/headers.py

response headers are meant to be assigned a Headers type object

add surrogate key outputs a headers object

---

arxiv/config/__init__.py
arxiv/db/models.py

It would be nice if we could configure all the features for the engine from env vars.

Adds statement_timeout for latexml db arxivce-2433

---

arxiv/base/static/js/member_acknowledgement.js

its being replaced by a permanent button in browse

removes addition of donate text link

---

gcp/cloud_functions/aggregate_hourly_downloads/src/main.py

count bad ids seperate from other unprocessable rows

clearer logging particularly for bad data

---

arxiv/ops/fastly_log_ingest/README.md
arxiv/ops/fastly_log_ingest/app.py
deploy/Dockerfile-fastlylogingest

Documents deploy.
Reduces replaces some log stack traces with simple messages.
Sets defults of values to be what is used in production.
Excessive error log messages by the app caused the CPU use on deployed vms.

Changes fastly_log_ingest error handling

---

gcp/cloud_functions/aggregate_hourly_downloads/src/main.py

create a manual backfill function
refactor so that the two can share code

Arxivce 2891 handle lack of data

---

arxiv/auth/user_claims.py

The access token can be in the authentication header.

Make the cookie simpler. Completely ditch the access token

---

arxiv/auth/legacy/util.py
arxiv/util/database_loader.py
arxiv/util/dict_io.py
development/test-data/arXiv_archive_group.json
development/test-data/arXiv_category_def.json
development/test-data/arXiv_licenses.json
poetry.lock
pyproject.toml

Data/script used for setting up the arxiv database for testing.

arXiv db test data and its loader.

---

gcp/cloud_functions/aggregate_hourly_downloads/README.md
gcp/cloud_functions/aggregate_hourly_downloads/cicd/env.aggregate_hourly_downloads.arxiv-development.yaml
gcp/cloud_functions/aggregate_hourly_downloads/cicd/env.aggregate_hourly_downloads.arxiv-production.yaml
gcp/cloud_functions/aggregate_hourly_downloads/src/main.py

hourly and manual functions now use the same consolidated query and processing functions.

update database query

---

poetry.lock
pyproject.toml

[fire v0.6.0 Release Notes](https://github.com/google/python-fire/releases/tag/v0.6.0)
Should be a minor upgrade.

update fire 0.6.0 to patch Cloud Build
